apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/OscarHagman/L2-ArgoCD
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp
  
  syncPolicy:
    syncOption:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true